language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
install: mvn clean install checksum:files -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn versioneye:update test jacoco:report
#after_success:
#- mvn coveralls:report
before_deploy:
  - export RELEASE_PKG_FILE=$(ls target/*.jar)
  - export RELEASE_PKG_MD5_FILE=$(ls target/*.jar.md5)
  - export RELEASE_PKG_SHA_FILE=$(ls target/*.jar.sha1)
  - echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE to GitHub releases"
env:
  global:
    secure: C9CU6IY8G3oas+Fsh8XOXtsQ+p5gN49j4hMRD8khdLHVSjLJCv+Y1IFoNi6typ9JSV0kPdohfyX2t2FS+tUHgxlU6IEJM0G0kRa08bK5jKo7NN1hHESfBda3UlMwEY+lvFSz+/gEI6Tjvldc/uPdiIX+uxWAru6IqCtqB/Gp5rY/0nUPQ9m4UWAMNlTHRDxMxQPMl8OyON8ZEcKCLSTTmXXdOnjwHCO7ywRY6Cuughnmb7MyGSqwSXe0QOaD//0V0Hm3X96yb2B7E9ZnmifzSlgP86pbkZg9g7gQu6nheCTbE4aLQkCqqwtDu3uFBm5XAbM4xpNkQwY+7gHbuXxzuQEgZXwc7ST/Ba6IegmIGoshjKe/bro22uoKl+wG7KDgxsJQa+SF9Thim+5YnuxwesnvRAxonFIBnZUjwS7vfTfWfpJoKO+yuxqvZ3t75kxXkuAzhHU0rw5oWJOL6gDLvkKrsoOTKalzKMNGKib2DopvC8/Zwi8UWr+0umEzlBeAx6FGkbVtWeCxWfh/s3Zm6A5vsOIlG5t4OWu/6X701/1c8rFer0xRjhN9po9/c9wycTPGAp+M3Ujh4yuTwcb+lARTSAynYw7TmVtuGLGmMkGgKYypx+p2QfaKpJNdiUFfGEw+BdMNDIhMwDOSE1a17JONdazzpXXWTY7meMYaBDg=
    secure: bjbbFoWDW/QbHuQQi6hHv3Ne/EamMWIKy/aDtT1TAswKOUnaroYyKZncsYENjGa7j0ZUgIu5w+c2GurB+WU/midavPhBT3rx5fBHr5cfnYir4rReQp8FZi6gXb1pGzhaf8E4Ic5tljaVNTIAo/hzXtTmtaHT3+OSlLZ2c4JvzKaeydmCZZFMuzdzkDBpsq58rQ8xzGAlfvB+jUqQ60P8vaAjtIgwICpvq4pmx3SlPSXdcr8mWAcoiSSoVgexVe99YIQ4dkQ7RHp3id/NfWru+CAZ4sB1saMmxheAWdKI82hb0Uu8dMuI7CN09gvDoc+M9dVkOBMWM5vdp984d0YxHrh8Pz6yIU4002RWgbk/sbf+aK167ixMMRHoEePWIlbO6awSPJt/eOYIcTIEY1uwcjDRyMMl4BZkhx0FjpX7iiM/+QglWl2k3M+SSbgzh6M4MjcGww13YMF/EvKcuuFwKs7BixfHo+FoXBc24sW5KlN3lu+yHThXSm93PDJoOUT61XHIXNijxzwHQEdPgYWe+Yj0eLzGZGfI9FtbNgp2iV14hUXMBKzSEnqY7IZpW9PxXDh6TrOZNM7Nvonwj1Eb4AAdNFqTy0EDal254vVq0OS4lBH2YFLSturvT4She3hF6qOhSEhPZI+pT0CAkBeDl2hrol9iBvr9UP04kW1RcI8=
notifications:
  slack:
    rooms:
        secure: jwh3b/KvyWY7eSPW17QtcuI3BNU4VPM7zE+mIZLKqZ7nAFlvMrCJ4FusR6rNPdxUvC9iaM4An3hT610MUNZb1ai9TZ0vC9JYo1g4n2q8C+BL10kSfOjema73htcQ2q73gqeiSnFidrbd0yRCnKAlqseRBNNhFJjEDHVJRuDRh8aB6k96yGcyZQylKQXz3krRpMzIbh+yRhbrh/9l+899y4X37nLpZMrQjl2rP/99fr+IbCv+VyTbKTHGCJg87wAY/3/I/OP6fpRpJ/9pypt0/pFgarWMet6+GaTg46HFjqqhldOmnBampL4Laz9aln8YGxHDS5yRYzZGrvOn2SHhpuods28b1x3x2J/Y5iP0x/aEc/e9Vms8rwUX+rrTqW7vk9RqImu2VeLvrc8kBqPAgtSWBceBEuuEw4DNvz02T+LcAzEY3BQY2cQ6RWst48WXXfgw8OuShJTkHBPI3eNsDMG0DpGILzMXZPbKY+LcaqWFL1B0YapCIOkddndSNVh99V0BS0KtxlIY2X8Vc3JGAJszYvGooGCDCoxR5tNIsWf5zj+RdwUKBxqWYhEhyctVPQCBWTQ1jFji9oIhSudQXD2Te0XLOuEpM0U43LmTjW9BPW4kqg0laW7SFzthzUO067W1DJ66N72/o2zKBOiCdkoBaIkC0I6G/BtybubQNNM=
deploy:
  provider: releases
  api_key:
    secure: UMYZaHnLLiv8/fl0JXIoIWCm+p+5V0mF1mjbJPOSlmG5SECUs23x/4rpbbyOG1IsHzc5xgNlKiJdwP0SHFykm/4WEWtrloAhLh4Cy4tFPVmj4wrTZVGs5Q8ths7aS0Izcy2GA3xHP64IA9QPf3UXFEehoYyevf5ye2bcEqR+IMLSvWBViEQ6iRUocmxfF1o+6tALdFTvOULsiXLb++3msgSVO2AaEaJquM4xgq5v5GRTLD3b5unKtFcmmyZd3X6f+GBB86x0sX7yLfMWhfOQhwsYGZfMVauWuHzf1kXD97bZ6gHTHXdH8SssYRAG58Wl4jBGpEOb4rnIq+UWRFaofw+NuXUzkuD6IzvVS/tHPeTnixBP6KfjLLbhejoyVDe0mRnNUyiLWw5JZSbW3RyclJP30fLCQYP2KQqEt8K8q1H6gqLosiJm1L/lP2iEaY70z2yePTsA0jYG3yhnAH+Nxu9qqlnevR5nZkDWHf2UDseWnvB65PoJrdyCrayKobHBdYGTesonwt7mchpH3346Xge+DXPafzqHT0l/dIewPrUTDfszPrGOrse9miT50LyCNEeLc2O5DnrdTCgTS87ksG0H5EOB7QmEhuoahF2VEYtrvPxe1QIznrkTjGtdBrWDlCS+h/0Ymfo2+64NyP1IpLl68Bcpwe3MeOiFJAdRuhE=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_PKG_MD5_FILE}"
  - "${RELEASE_PKG_SHA_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: Cute-DB/cute-db-server

